### ISSUE TITLE
Mixin Conflict with NEA

### ISSUE THREAD

**Issue by brachy84** [CaliforniaDemise/Bundles#1]
Your [ContainerMixin](https://github.com/CaliforniaDemise/Bundles/blob/main/src/main/java/surreal/bundles/mixins/early/ContainerMixin.java) conflicts with my [ContainerMixin](https://github.com/CleanroomMC/NeverEnoughAnimation/blob/master/src/main/java/com/cleanroommc/neverenoughanimations/core/mixin/ContainerMixin.java) due to you overwriting the whole method.
The specific error is `org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/inventory/Container::pickupAllPre with priority 1000 cannot inject into net/minecraft/inventory/Container::func_184996_a(IILnet/minecraft/inventory/ClickType;Lnet/minecraft/entity/player/EntityPlayer;)Lnet/minecraft/item/ItemStack; merged by surreal.bundles.mixins.early.ContainerMixin with priority 1000 [ -> handler$zzd000$pickupAllPre(IILnet/minecraft/inventory/ClickType;Lnet/minecraft/entity/player/EntityPlayer;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lcom/llamalad7/mixinextras/sugar/ref/LocalRef;)V -> Prepare]`.

**Comment by CaliforniaDemise** [comment]
Fixed.
