### ISSUE TITLE
Bundles don't seem to work with latest Mouse Tweaks Unnoficial version

### ISSUE THREAD

**Issue by Henrykado** [CaliforniaDemise/Bundles#2]
Without Mouse Tweaks it works fine, but with it you can't put items inside the bundle.
Also i'm using the default config.

**Comment by CaliforniaDemise** [comment]
Not an issue on bundles' side, rather on mixins' side. This means some other mixin mods that use mixin extras might not work too. I will not use mixin extras until this issue gets fixed. New release should work properly.
